### PR TITLE
link to attend form

### PR DESCRIPTION
**Pull request by nickdesaulniers**

### CODE REVIEW

**Comment by nathanchance** [comment]
I assume it is intentional that the form is not viewable at the moment?

**Comment by bwendling** [comment]
> I assume it is intentional that the form is not viewable at the moment?

No it's not. >_< I'll try to make it public.

**Comment by bwendling** [comment]
Please check again to see if it's viable now.

**Comment by nathanchance** [comment]
> Please check again to see if it's viable now.

It is, thanks!

**Pull request merged**
